"""add text render bounds

Revision ID: 6292332f631a
Revises: d4e5f6a7b8c9
Create Date: 2026-04-28 02:32:33.940422

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6292332f631a'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_texts', sa.Column('render_bounds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_texts', 'render_bounds')
    # ### end Alembic commands ###
